[package]
name = "IOKit-sys"
version = "0.1.0"
authors = ["David Cuddeback <david.cuddeback@gmail.com>"]

links = "IOKit"
build = "build.rs"

[dependencies]
libc = "0.1.8"
CoreFoundation-sys = "0.1.0"
